---
apiVersion: v1
kind: Secret
metadata:
    name: secret
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: bot
    name: bot
spec:
    replicas: 1
    selector:
        matchLabels:
            service: bot
    template:
        metadata:
            labels:
                service: bot
        spec:
            containers:
                - env:
                      - name: BOT_ID
                        valueFrom:
                            secretKeyRef:
                                key: BOT_ID
                                name: secret
                      - name: BOT_TOKEN
                        valueFrom:
                            secretKeyRef:
                                key: BOT_TOKEN
                                name: secret
                      - name: CREATE_THREAD
                        valueFrom:
                            secretKeyRef:
                                key: CREATE_THREAD
                                name: secret
                      - name: PW_SERVER_URL
                        valueFrom:
                            secretKeyRef:
                                key: PW_SERVER_URL
                                name: secret
                  image: ghcr.io/jacoblincool/convease
                  name: bot
                  resources:
                      limits:
                          cpu: "2"
                          memory: "2147483648"
                      requests:
                          cpu: 500m
                          memory: "134217728"
            restartPolicy: Always
