---
apiVersion: v1
kind: Service
metadata:
    labels:
        service: chromium
    name: chromium
spec:
    ports:
        - name: "53333"
          port: 53333
          targetPort: 53333
    selector:
        service: chromium

---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: chromium
    name: chromium
spec:
    replicas: 1
    selector:
        matchLabels:
            service: chromium
    template:
        metadata:
            labels:
                service: chromium
        spec:
            containers:
                - image: ghcr.io/jacoblincool/chromium-server-cjk
                  readinessProbe:
                      exec:
                          command:
                              - nc
                              - -z
                              - localhost
                              - "53333"
                  livenessProbe:
                      exec:
                          command:
                              - nc
                              - -z
                              - localhost
                              - "53333"
                  name: chromium
                  ports:
                      - containerPort: 53333
                        hostPort: 53333
                        protocol: TCP
                  resources:
                      limits:
                          cpu: "2"
                          memory: "4294967296"
                      requests:
                          cpu: 500m
                          memory: "134217728"
            restartPolicy: Always
