apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: convease
resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/JacobLinCool/ConvEase/main/deployment/kubernetes/bot.yml
  - https://raw.githubusercontent.com/JacobLinCool/ConvEase/main/deployment/kubernetes/chromium.yml
generators:
  - ./secret-generator.yaml
