apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/install.yaml
patches:
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-cm.yaml
  - path: argocd-repo-server-ksops.yaml
secretGenerator:
  - name: argocd-secret
    behavior: merge
    envs:
      - .env
