apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: argocd-secret
      annotations:
        kustomize.config.k8s.io/behavior: merge
    envs:
      - ./enc.env
files:
  - ./deploy-key-secret.enc.yaml
