apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app: cloudflared
resources:
  - namespace.yaml
  - deployment.yaml
generators:
  - ./secret-generator.yaml
