apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: cloudflared
resources:
  - deployment.yaml
secretGenerator:
  - name: cloudflare-tunnel-secret
    envs:
      - .env
