apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: cloudflare-tunnel-secret
      namespace: cloudflared
    envs:
      - ./enc.env
